import { createFileRoute } from '@tanstack/react-router';
import { PolicyLayout } from '@/components/jnoy/PolicyLayout';

export const Route = createFileRoute('/terms')({
  head: () => ({ meta: [
    { title: 'Terms of Service — Jnoy' }, { name: 'description', content: 'The rules for using Jnoy random video, voice and text chat, worldwide.' },
    { property: 'og:title', content: 'Terms of Service — Jnoy' }, { property: 'og:description', content: 'The rules for using Jnoy random video, voice and text chat.' },
    { property: 'og:type', content: 'article' }, { name: 'twitter:card', content: 'summary' },
  ] }),
  component: () => <PolicyLayout title="Terms of Service" updated="30 SEP 2026" intro="These Terms form a binding agreement between you and Jnoy (“we”, “us”). By creating an account or using Jnoy you agree to them. If you do not agree, do not use the service." sections={[
    { h: 'Eligibility — adults only (18+)', p: ['Jnoy is strictly for people aged 18 or older, or the age of majority where you live if higher (for example 19 in parts of Canada and South Korea, 20 in Thailand, 21 in some jurisdictions for certain services). By signing up you confirm you meet this requirement.', 'We act on reports of underage users and remove such accounts. Knowingly allowing a minor to use Jnoy violates these Terms and may break laws such as the US Children’s Online Privacy Protection Act (COPPA), the EU/UK GDPR rules on children’s data, and India’s Digital Personal Data Protection Act 2023 (DPDP Act).'] },
    { h: 'Your account', p: ['You must give accurate information (first and last name, gender, age, country and language) and keep your sign-in secure. One person, one account. You are responsible for all activity on your account.', 'You may delete your account at any time. We may suspend or close accounts that break these Terms or the Community Guidelines.'] },
    { h: 'How matching works', p: ['Jnoy pairs you at random with other adults. We rank candidates by country, region, language, shared tags and waiting time, then widen to the whole world. You cannot search for or choose specific people. Tapping Next ends the current conversation and clears its chat for you.'] },
    { h: 'Acceptable use', p: ['You agree not to:', ['share nudity, sexual content, or any content involving minors;', 'harass, threaten, bully, stalk, or discriminate against anyone;', 'record, screenshot or rebroadcast other users without their consent (except the automatic safety snapshot taken when you report);', 'share phone numbers, emails, social handles or other contact details in chat;', 'spam, advertise, scam, phish or impersonate anyone;', 'use bots, scrapers, or attempt to bypass safety systems or bans;', 'break any local law, including laws on obscenity, hate speech, and interception of communications.']] },
    { h: 'Moderation and safety review', p: ['To protect users, conversation chat text, reports, and safety snapshots may be reviewed by our trained safety staff. Every staff view is logged. We may warn, suspend or permanently ban accounts, and we report child sexual abuse material to the relevant authorities (for example NCMEC in the US, and national law enforcement elsewhere).'] },
    { h: 'User content', p: ['You keep ownership of what you say and share. You grant us a limited licence to transmit it to your match and to store it as described in the Privacy Policy for safety and legal compliance.'] },
    { h: 'No guarantees', p: ['Jnoy connects you with strangers. We cannot guarantee how others behave. The service is provided “as is” to the fullest extent permitted by law. Nothing in these Terms limits rights you have under mandatory consumer law in your country (for example the EU Consumer Rights Directive, the UK Consumer Rights Act 2015, the Australian Consumer Law, or India’s Consumer Protection Act 2019).'] },
    { h: 'Limitation of liability', p: ['To the extent allowed by law, we are not liable for indirect or consequential losses, or for the conduct of other users. Where liability cannot be excluded, it is limited to the amount you paid us in the last 12 months (Jnoy is currently free).'] },
    { h: 'Governing law and disputes', p: ['These Terms are governed by the laws of India, without affecting any mandatory protection you have under the law of your country of residence. EU and UK consumers may bring claims in their local courts. Before any claim, please contact us so we can try to resolve it.'] },
    { h: 'Changes and contact', p: ['We will notify you of material changes in the app. Continuing to use Jnoy after changes means you accept them. Questions: legal@jnoy.app. Grievance Officer (India IT Rules 2021): grievance@jnoy.app — we acknowledge complaints within 24 hours and resolve them within 15 days.'] },
  ]}/>,
});
