REVOKE EXECUTE ON FUNCTION public.accept_terms() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.complete_onboarding(text,text,text,int,text,text,text[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.submit_report_v2(uuid,uuid,text,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_users_v2(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_user_sessions(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_session_messages(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_user_visits(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.join_match_queue(text,jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.find_or_create_match() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;